## name basic failure
## failures 1
## cut

my $regex = qr(asdf);
if ( $string =~ /$regex/m ) {
}

#-----------------------------------------------------------------------------

## name no modifier
## failures 0
## cut

my $regex = qr(asdf);
if ( $string =~ /$regex/ ) {
}

#-----------------------------------------------------------------------------

## name regex is just a string
## failures 0
## cut

my $regex = 'asdf';
if ( $string =~ /$regex/m ) {
}

#-----------------------------------------------------------------------------

## name regex is not simply a qr() expression
## failures 0
## cut

my $regex = qr(asdf);
if ( $string =~ /foo$regex/m ) {
}

#-----------------------------------------------------------------------------

## name Do not warn if the qr() is modified in the same way
## failures 0
## TODO not handled yet
## cut

my $regex = qr(asdf)m;
if ( $string =~ /$regex/m ) {
}

#-----------------------------------------------------------------------------
