## name Acceptable Comments
## failures 0
## cut

my $foo = '#XXX';
# this comment is OK
my $XXX = 'foo';
my $SITE_XXX = 'foo';
# Site_XXX is also OK

#-----------------------------------------------------------------------------

## name Unacceptable Comments
## failures 3
## cut

# XXX I need to fix this comment
# I need to FIXME this
# TODO-Change this

#-----------------------------------------------------------------------------

## name Special Characters
## parms { keywords => 'WE*RD' };
## failures 0
## cut

# WEIRD
# WERD

#-----------------------------------------------------------------------------

## name Special Characters failing
## parms { keywords => 'WE*RD' };
## failures 1
## cut

# WE*RD
# WEIRD

#-----------------------------------------------------------------------------

## name Flags in POD
## failures 1
## cut

=head1 SYNOPSIS

=over 4

FIXME: needs a description

=item one

TODO

=back

=cut

#-----------------------------------------------------------------------------

## name Flags as POD
## failures 0
## parms { exempt_pod => 1 };
## cut

=head1 TODO

=cut

#-----------------------------------------------------------------------------

# ex: set ft=perl:
