## name Acceptable Comments
## failures 0
## cut

my $foo = '#XXX';
# this comment is OK
my $XXX = 'foo';

#-----------------------------------------------------------------------------

## name XXX Comments
## failures 1
## cut

# XXX I need to fix this comment

#-----------------------------------------------------------------------------

## name Flags in POD
## failures 1
## cut

=head1 SYNOPSIS

=over 4

FIXME: needs a description

=item one

TODO

=back

=cut

#-----------------------------------------------------------------------------

## name Flags as POD
## failures 1
## cut

=head1 TODO

=cut

#-----------------------------------------------------------------------------

# ex: set ft=perl:
